POST http://localhost:8181/index/cards

### search
POST http://localhost:8181/index/products/search
Content-Type: application/json

{
  "searchString": "ваза керамическая синяя",
  "filters": [{
    "type": "single",
    "field": "category",
    "value": "декор для дома"
  }],
  "sortBy": "price",
  "nextPage": "eyJwaXQiOiJrLVdBUVFNSWNISnZaSFZqZEhNV2FFbFZRWGRpY0hCVGVXbHBSa0oxTWw5aGRFVjVRUUFXVkZKVFUwbzFlRnBUTWkxUFdXdE5VRmRZZEVGRVp3QUFBQUFBQUFBQXpoWjZWa3c1VUdKa1NGUnNhVWRvTUhVd1kwZENMVWhuQ0hCeWIyUjFZM1J6Rm1oSlZVRjNZbkJ3VTNscGFVWkNkVEpmWVhSRmVVRUJGbVJLYzJkVlEySm9VVU5oVFhBemVETmZTMU5pWlhjQUFBQUFBQUFBQUdNV1dtdGFNa010VlhWU01HVXpYemMxVG5KWlRGUm9ad2h3Y205a2RXTjBjeFpvU1ZWQmQySndjRk41YVdsR1FuVXlYMkYwUlhsQkFoWmtTbk5uVlVOaWFGRkRZVTF3TTNnelgwdFRZbVYzQUFBQUFBQUFBQUJrRmxwcldqSkRMVlYxVWpCbE0xODNOVTV5V1V4VWFHY0JGbWhKVlVGM1luQndVM2xwYVVaQ2RUSmZZWFJGZVVFQUFBPT0iLCJzb3J0VmFsdWVzIjpbMTcwMC4wLDI0LjQ5NTM4Ml19"
}

### filter
POST http://localhost:8181/index/filter/products
Content-Type: application/json

{
  "category": "одежда",
  "sort": {
    "sortBy": "price"
  }
}

### filter: scroll to next page
POST http://localhost:8181/index/filter/products
Content-Type: application/json

{
  "pit": "k-WAQQMIcHJvZHVjdHMWcVQyeHp3WGhUTmVCWkljM2VxQkNjZwEWZEpzZ1VDYmhRQ2FNcDN4M19LU2JldwAAAAAAAAAAJhZDUFU0XzZ6blRCZW05RzE1VG9kdUZnCHByb2R1Y3RzFnFUMnh6d1hoVE5lQlpJYzNlcUJDY2cCFmRKc2dVQ2JoUUNhTXAzeDNfS1NiZXcAAAAAAAAAACcWQ1BVNF82em5UQmVtOUcxNVRvZHVGZwhwcm9kdWN0cxZxVDJ4endYaFROZUJaSWMzZXFCQ2NnABZkSnNnVUNiaFFDYU1wM3gzX0tTYmV3AAAAAAAAAAAlFkNQVTRfNnpuVEJlbTlHMTVUb2R1RmcBFnFUMnh6d1hoVE5lQlpJYzNlcUJDY2cAAA==",
  "category": "одежда",
  "sort": {
    "sortBy": "price",
    "value": 1600.0
  }
}

### create test data
POST http://localhost:8181/index/create-test-data