POST http://localhost:8181/index/cards

### get categories
GET http://localhost:8181/categories/v1
Accept: application/json

### get category
GET http://localhost:8181/categories/v1/a25f4003-5311-45d0-b4bf-bd67bacbfd89
Accept: application/json

### categories init
POST http://localhost:8181/categories/v1/init
Accept: application/json

### attrs types
GET http://localhost:8181/categories/v1/attrs/types
Accept: application/json

### attrs predefined
GET http://localhost:8181/categories/v1/attrs/predefined
Accept: application/json

### get category attrs
GET http://localhost:8181/categories/v1/a25f4003-5311-45d0-b4bf-bd67bacbfd89/attrs
Accept: application/json

### delete attr
DELETE http://localhost:8181/categories/v1/a25f4003-5311-45d0-b4bf-bd67bacbfd89/attrs/4d229f9d-5502-477f-b57c-620e87da3a88

### search
POST http://localhost:8181/index/products/search
Content-Type: application/json

{
  "searchString": "ваза декоративная керамическая красная для сухоцветов",
  "filters": [{
    "type": "single",
    "field": "category",
    "value": "декор для дома"
  }]
}

### filter
POST http://localhost:8181/index/filter/products
Content-Type: application/json

{
  "category": "одежда",
  "sort": {
    "sortBy": "price"
  }
}

### filter: scroll to next page
POST http://localhost:8181/index/filter/products
Content-Type: application/json

{
  "pit": "k-WAQQMIcHJvZHVjdHMWcVQyeHp3WGhUTmVCWkljM2VxQkNjZwEWZEpzZ1VDYmhRQ2FNcDN4M19LU2JldwAAAAAAAAAAJhZDUFU0XzZ6blRCZW05RzE1VG9kdUZnCHByb2R1Y3RzFnFUMnh6d1hoVE5lQlpJYzNlcUJDY2cCFmRKc2dVQ2JoUUNhTXAzeDNfS1NiZXcAAAAAAAAAACcWQ1BVNF82em5UQmVtOUcxNVRvZHVGZwhwcm9kdWN0cxZxVDJ4endYaFROZUJaSWMzZXFCQ2NnABZkSnNnVUNiaFFDYU1wM3gzX0tTYmV3AAAAAAAAAAAlFkNQVTRfNnpuVEJlbTlHMTVUb2R1RmcBFnFUMnh6d1hoVE5lQlpJYzNlcUJDY2cAAA==",
  "category": "одежда",
  "sort": {
    "sortBy": "price",
    "value": 1600.0
  }
}

### create test data
POST http://localhost:8181/index/create-test-data

### spacy POS analyze text
POST http://localhost:8765/analyze
Content-Type: application/json

{
  "text": "ваза декоративная красная и синяя подставка"
}