server:
  port: 8181
  servlet:
    context-path: "/"

opensearch:
  uris: http://localhost:9200
  username: admin
  password: admin

springdoc:
  api-docs:
    path: /api-docs
    enabled: true

logging:
  level:
    org:
      opensearch: TRACE